# Generated by Django 3.2.7 on 2021-09-19 09:38

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30, null=True), blank=True, default=list, size=None)),
                ('quote', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30, null=True), blank=True, default=list, size=None)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
