# Generated by Django 3.2.7 on 2021-09-19 03:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('_id', models.CharField(max_length=30, primary_key=True, serialize=False, unique=True)),
                ('height', models.CharField(blank=True, max_length=50)),
                ('race', models.CharField(blank=True, max_length=50)),
                ('gender', models.CharField(blank=True, max_length=50)),
                ('birth', models.CharField(blank=True, max_length=50)),
                ('spouse', models.CharField(blank=True, max_length=50)),
                ('death', models.CharField(blank=True, max_length=50)),
                ('realm', models.CharField(blank=True, max_length=50)),
                ('hair', models.CharField(blank=True, max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('wikiUrl', models.URLField(blank=True)),
                ('liked_by', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('_id', models.CharField(max_length=30, primary_key=True, serialize=False, unique=True)),
                ('dialog', models.TextField()),
                ('movie', models.CharField(max_length=30)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quote', to='core.character')),
                ('liked_by', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
